name: sense_food
description: "A new Flutter project for CASA0015."
publish_to: 'none'

version: 1.1.1+3

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Core libraries for the project ---

  # 1. State Management & Permissions (Base Logic)
  provider: ^6.1.1
  permission_handler: ^11.3.1
  geocoding: ^3.0.0

  # 2. Sensors & Physical Environment (Connected Environment)
  geolocator: ^13.0.1           # GPS Positioning
  noise_meter: ^5.0.0           # Microphone decibel monitoring

  # 3. External Services & AI (API Integration)
  google_generative_ai: ^0.4.5  # Google Gemini AI image recognition
  firebase_core: ^3.6.0         # Firebase Core
  cloud_firestore: ^5.0.2       # Firestore cloud database (History storage)
  firebase_auth: ^5.3.1         # Account/Password Login

  # 4. Advanced UI & Data Recording (UI Components)
  fl_chart: ^0.69.0             # Statistical charts
  table_calendar: ^3.1.2        # Diet log with calendar
  google_maps_flutter: ^2.7.0   # Crowdsourced map display
  image_picker: ^1.1.2          # Camera and gallery selection

  # 5. Security & Environment Variables (For hiding API Keys)
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "sensefood"
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  # Register .env file for app runtime key access
  assets:
    - .env
